site_name: Work Items Gantt by Nextedy Systems
site_description: 'A set of Polarion Extensions to enable project scheduling in Polarion ALM'
site_author: 'Nextedy'

nav:
    - Getting Started: index.md
    - Setup: setup.md
    - Widget: widget.md
    - Download: download.md
    - Release Notes: changelog.md
    - Pricing: pricing.md
    - Support: support.md
    - About: about.md

theme:
  name: 'material'
  font: false
  palette:
    primary: 'blue'
    accent: 'red'
  favicon: img/favicon.png
    

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - tables
  
  
google_analytics:
  - 'UA-125777914-2'
  - 'auto'
  
copyright: 'Copyright &copy; 2019 Nextedy Systems'
  