site_name: Nextedy GANTT
site_description: 'The first interactive high-level project planning & scheduling in Polarion ALM.'
site_author: Nextedy
site_url: https://gantt.nextedy.com
site_GTM_ID: GTM-PMZ3VRL
site_HS_ID: 6265870

nav:
    - Home: index.md
    - Setup: setup.md
    - Widgets:
       - Work Items Gantt Widget: widget.md
       - Plan Gantt Widget: widget-plan.md
       - Configuration Properties: context-properties.md      
    - Download: download.md
    - Pricing: pricing.md          
    - Support: support.md 
    - News: news.md
    - About us: about.md

theme:
  name: 'material'
  font: false
  palette:
    primary: 'black'
    accent: 'red'
  favicon: img/favicon.png
  custom_dir: 'theme'
  logo: 'https://www.nextedy.com/wp-content/uploads/2018/10/nextedy-logo.png'


extra_css:
  - 'extra/extra.css'
  - 'extra/simpleLightbox.min.css'
  - 'extra/semantic/dist/semantic.min.css'
  
extra_javascript:
  - 'extra/extra.js'
  - 'extra/simpleLightbox.min.js'
  - 'extra/jquery-3.1.1.min.js'  
  - 'extra/semantic/dist/semantic.min.js' 
  
extra:
  product:
     name: Nextedy GANTT
     url: https://gantt.nextedy.com
     requirements: Polarion 18.1 and newer   
  support:
     solution: 48000031169
     installGuide: https://gantt.nextedy.com/setup/    
  hs:
     id: 6265870
     quoteFormId: c14213f2-29be-4184-987a-b2da34e44422
     downloadFormId: 385aed16-fb7a-469c-a416-b644cca90b05
  other1:
     name: Nextedy WORKSHEET
     url: https://worksheet.nextedy.com
     image: https://worksheet.nextedy.com/img/worksheet-all-thumb.png
     description: Interactive Work Tracking and Team Assignments for Polarion ALM.
  other2:
     name: Nextedy CHECKLIST
     url: https://checklist.nextedy.com
     image: https://checklist.nextedy.com/img/checklist.png
     description: Extend your Polarion with action-able checklists to support your workflow process.
  
markdown_extensions:
  - admonition
  - codehilite
  - meta
  - tables
  - attr_list

plugins:
    - search
    - markdownextradata: {}
    - redirects:
        redirect_maps:
            'about.md': 'https://www.nextedy.com/company/'
            'download.md': 'https://www.nextedy.com/product/nextedy-gantt/#download'
            'index.md': 'https://www.nextedy.com/product/nextedy-gantt/'
            'news.md': 'https://www.nextedy.com/news/'
            'pricing.md': 'https://www.nextedy.com/product/nextedy-gantt/#faq'
            'support.md': 'https://www.nextedy.com/product/nextedy-gantt/#support'  
            'setup.md': 'https://nextedy.freshdesk.com/support/solutions/articles/48000354777-install-and-setup-gantt-'  
            'widget.md': 'https://nextedy.freshdesk.com/support/solutions/articles/48001074061-work-items-gantt-widget-parameters'  
            'widget-plan.md': 'https://nextedy.freshdesk.com/support/solutions/articles/48001074062-plans-gantt-widget-parameters'  
            'context-properties.md': 'https://nextedy.freshdesk.com/support/solutions/articles/48001074063-gantt-configure-default-values-and-properties'  

copyright: 'Copyright &copy; 2020 Nextedy Systems'
  